name: train-management
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: TrainManagement
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - train-management
      - hspec
